### ISSUE TITLE
GERBIL is not accepting external annotators.

### ISSUE THREAD

**Issue by DiegoMoussallem** [dice-group/gerbil#222] opened 2017-11-06 18:09 UTC
I wasn't able to connect FOX's webservice (http://fox-demo.aksw.org/fox) to GERBIL and also an external AGDISTIS's webservice. No error message was shown just "Please wait while the communication with your annotator is tested...".  I assumed something wrong is going on in the back end because I checked it twice in different days.

**Comment by MichaelRoeder** [comment] 2017-11-07 09:17
GERBIL got stuck in a rehashing loop. All running experiments try to communicate via HTTP but the HTTP management is not able to store the information that it got because its Hash map seems to have an internal problem. All threads keep rehashing their objects without making any real progress.

```
eTConfig("SomeAnnotator","SomeDataset","D2KB","STRONG_ANNOTATION_MATCH")
state=RUNNABLE
progress=null
java.lang.Object.hashCode(Native Method)
org.aksw.gerbil.http.ObservedHttpRequest.hashCode(ObservedHttpRequest.java:35)
com.carrotsearch.hppc.Internals.rehash(Internals.java:10)
com.carrotsearch.hppc.ObjectLongOpenHashMap.shiftConflictingKeys(ObjectLongOpenHashMap.java:462)
com.carrotsearch.hppc.ObjectLongOpenHashMap.remove(ObjectLongOpenHashMap.java:438)
org.aksw.gerbil.http.InterruptingObserver.reportEnd(InterruptingObserver.java:106)
org.aksw.gerbil.http.HttpManagement.reportEnd(HttpManagement.java:151)
org.aksw.gerbil.http.AbstractHttpRequestEmitter.closeRequest(AbstractHttpRequestEmitter.java:124)
org.aksw.gerbil.dataset.check.impl.HttpBasedEntityChecker.entityExists(HttpBasedEntityChecker.java:77)
org.aksw.gerbil.dataset.check.impl.EntityCheckerManagerImpl.checkUri(EntityCheckerManagerImpl.java:135)
org.aksw.gerbil.dataset.check.impl.FileBasedCachingEntityCheckerManager.checkUri(FileBasedCachingEntityCheckerManager.java:152)
org.aksw.gerbil.dataset.check.impl.EntityCheckerManagerImpl.checkMeaning(EntityCheckerManagerImpl.java:84)
org.aksw.gerbil.dataset.check.impl.EntityCheckerManagerImpl.checkMarkings(EntityCheckerManagerImpl.java:64)
org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getPreparedDataset(AbstractDatasetConfiguration.java:79)
org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getDataset(AbstractDatasetConfiguration.java:50)
org.aksw.gerbil.execute.ExperimentTask.run(ExperimentTask.java:102)
org.aksw.simba.topicmodeling.concurrent.workers.WorkerImpl.run(WorkerImpl.java:44)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
```

The same holds for the communication test that is executed internally when you added the webservice because it tries to do the same and gets stuck as well.

I will restart the server and close this ticket after that since it is a duplicate of #177

**Closed** 2017-11-07 09:23 UTC
Labels: bug
