### ISSUE TITLE
[QA] Issue with exact F-measures

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/gerbil#211] opened 2017-09-01 14:51 UTC
Please work together with @D063520 to resolve issues around the exact F-measure. The QANARY framework gets different Fmeasure than we do.

**Comment by D063520** [comment] 2017-09-21 07:58
What is the status of this? Did you change the computation of the f-measures meanwhile

**Comment by RicardoUsbeck** [comment] 2017-09-21 10:43
@JonathanHuthmann ?

**Comment by JonathanHuthmann** [comment] 2017-09-26 18:06
@D063520
No, we didn't change the computation of the f-measure. 
Here is a CSV , containing all questions of the qald-7-train-multilingual dataset, with system answers , golden answers, and computed f-measure. Please compute the f measure for yourself to find differences.

[qald-7-train-multilingual.jsonFMeasure_and_system_answers.zip](https://github.com/dice-group/gerbil/files/1334357/qald-7-train-multilingual.jsonFMeasure_and_system_answers.zip)

The CSV columns are ordered the following way:
`question-id ; question_in_english ; microPrecision ; microRecall ; microF1 ; macroPrecision ; macroRecall ; macroF1 ; system_answers ; golden_answers_from_dataset`

**Comment by D063520** [comment] 2017-09-27 08:57
Hi, 

thank you, this is really helpful to debug. I found at least on error. Look at question 13. The system gives back only "Bremerhaven" which is correct. So the precision should be 1 but is zero. Can you correct this and we continue like this recursively?

Salut
Dennis

**Comment by D063520** [comment] 2017-09-27 08:58
One we have done this we should proceed with wikidata! There there was the main difference in f-measure!

**Comment by RicardoUsbeck** [comment] 2017-09-27 09:10
Hint: Please write for this case a unit test. The F-measure must be 2/7.

`13; Which cities does the Weser flow through?; 0.0; 0.0; 0.0; 0.0; 0.0; 0.0; [http://dbpedia.org/resource/Bremerhaven]; [http://dbpedia.org/resource/Fulda_(river), http://dbpedia.org/resource/Kassel, http://dbpedia.org/resource/Minden, http://dbpedia.org/resource/Bremerhaven, http://dbpedia.org/resource/Bremen, http://dbpedia.org/resource/Hamelin, http://dbpedia.org/resource/Hann._Münden] `

**Comment by TortugaAttack** [comment] 2017-09-27 14:22
@D063520 can you send me your f measure etc. for wikidata? Then i will check into that ;)

**Comment by D063520** [comment] 2017-09-27 14:25
what you mean, a file with the scores per question?

**Comment by TortugaAttack** [comment] 2017-09-27 14:26
it is sufficient for me only your final results (macro and micro) 
so i can check more easily with our results. ;)

**Comment by D063520** [comment] 2017-09-27 14:34
In fact it is a good question, I do not know anymore which is the version that is online, give me some time ....

**Comment by TortugaAttack** [comment] 2017-09-27 14:36
sure thing. just write it and i will check it ;)

**Comment by D063520** [comment] 2017-09-27 14:43
If I'm not wrong the numbers are:
Global precision 0.3675771421951543
Global recall 0.3940859858532273
Global F-measure 0.38037025851640766
If they are slightly around it is my error because the online version and the one that I just tested differ slightly. But as far as I remember the difference to what gerbil gave was very big.

**Comment by TortugaAttack** [comment] 2017-09-27 14:49
Thanks. I will look into it. 
One more question though. Was is the qald7 test or train dataset?

**Comment by D063520** [comment] 2017-09-27 15:00
Train. Thank you

**Comment by TortugaAttack** [comment] 2017-09-27 15:02
i see... 
I will try to find whats the exact problem, doing a little debug session the next days.

**Comment by TortugaAttack** [comment] 2017-09-28 16:53
okay, there was a problem with the owl:sameAs Retrieval. 
I fixed it, and got the following macro (global) measures

f1: 0.2279 
precision: 0.2365 
recall: 0.2699

I will do a debug file as jonathan did and provide it. 
so we can look whats the problem.

**Comment by D063520** [comment] 2017-09-28 17:14
One question ... why do you need owl:sameAs links? The gold standard uris are given. By the way since I'm not sure which version is online, I can put tomorrow one online and then you do the file. Or if you can do the file easily it is even better and we can try multiple times.

**Comment by TortugaAttack** [comment] 2017-09-28 17:32
f.e. Qanary answers with dbpedia resources and the gold standard uris are wikidata. To compare if both are the same owl:sameAs links are used which assures that they are the same ;) 
cool. just tell me when you put it online tomorrow ;)

**Comment by D063520** [comment] 2017-09-28 17:36
No wait .... then there is a missunderstanding! We can also do QA over wikidata the service is:
curl --data "query=Who is the wife of Barack Obama" https://wdaqua-qanary.univ-st-etienne.fr/gerbil-execute/wdaqua-core0-wikidata,%20QueryExecuter/

**Comment by D063520** [comment] 2017-09-28 17:37
But the other feature is also cool! I will use it soon : )

**Comment by TortugaAttack** [comment] 2017-09-28 17:51
awesome. 
I will test it tomorrow with the wikidata service and will check if i got better results ;)

**Comment by TortugaAttack** [comment] 2017-09-29 06:17
nice. 
The wikidata webservice provides the following results: 
f1 | precision | recall
-- | -- | --
0.3423 | 0.3447 | 0.3918

I will close the issue as soon as i got the same results with the sameAs Retrieval

**Comment by D063520** [comment] 2017-09-29 07:17
Very good. But do not close the issue please. I now put online the version with the over mentioned measures. Can you check if you can exactly reproduce the results. I think it is very important, we are trying to have a benchmark platform for the next years and the numbers must be right at least to 99%. If later at sometime it will come out that they are not exact it will be a mess and a problem for the whole community!

**Comment by TortugaAttack** [comment] 2017-09-29 08:03
let me know when the version is online 
Link stays the same?

**Comment by D063520** [comment] 2017-09-29 08:07
Yes the version is online and the link is the same.

**Comment by TortugaAttack** [comment] 2017-09-29 08:16
ok. seems to be the same results. I randomly checked the results of qanary as well as the gold standard and it seems correct. 
I will generate a debug file and send it to you

**Comment by D063520** [comment] 2017-09-29 08:19
ok, one problem can be that we evaluate slightly differently, I compare my results with the results of the SPARQL queries which you compare with the URI answer set. Since the dataset changed this could also be a reason. Anyway, if you send me the file I will check against my results.

**Comment by TortugaAttack** [comment] 2017-09-29 08:21
ah i see. I forgot to turn on the derive option (using the SPARQL Queries to sync results). 
I will check that again and generate the debug output directly with it. ;)

**Comment by TortugaAttack** [comment] 2017-09-29 10:03
the derive option has a bug... 
here are the unsynced results

[issue211.zip](https://github.com/dice-group/gerbil/files/1343898/issue211.zip)

**Comment by TortugaAttack** [comment] 2017-09-29 10:42
this is what i got with fixed sync. 

**f1**: 0.3516 
**precision**: 0.3576 
**recall**: 0.3841

[issue211_sparql.zip](https://github.com/dice-group/gerbil/files/1344015/issue211_sparql.zip)

**Comment by D063520** [comment] 2017-09-29 11:28
Hi, 

I do not really understand Annotator Answers. I'm pretty sure that I do not give back uris containing "viaf." like in the first question. Besides that the numbers seams roughly right. I found at least one error. But it seams to be an error in the dataset. Question 7 "Was the wife of president Lincoln called Mary?". If I execute the given SPARQL query I get true but the answer says false (https://wdaqua-frontend.univ-st-etienne.fr/question?query=president%20lincoln%20wife&lang=en&kb=wikidata). So the answer should be corrected in the dataset (I created a pull request). If I change in your sheet exactly that the precision and recall match. Jackpot! 🎉 🎊 

So wikidata is working from my side. As soon as you have pushed the changes let me now and I will test it myself online.

What is about dbpedia?

**Comment by TortugaAttack** [comment] 2017-09-29 11:36
perfect! 
no no, your service only provides the wikidata urls. But the sameAs retrieval was on and thus all of the sameAs uris are in the answerset. 

It now works with the DBpedia webservice too (exact same results) 
I will commit right now ;)

**Comment by RicardoUsbeck** [comment] 2017-09-29 11:37
I also accepted the pull request. Thus, we should soon be able to deploy a new qa.datasets and qa.commons version (see https://github.com/dice-group/NLIWOD)

**Comment by TortugaAttack** [comment] 2017-09-29 11:40
good point, the synchronization of the gold standard needs a new qa.commons too. 
Will commit the solution there as well. 
And we have to remember to first deploy the qa.* and then can deploy gerbil

**Comment by TortugaAttack** [comment] 2017-09-29 11:42
Plus i will submit a new issue as the Uri used for the sync should be dataset dependent and not globally. (we need a different URL for the wikidata set than the other sets)

**Comment by D063520** [comment] 2017-09-29 11:49
Ok, let me know when is ready and I will check directly. One last issue. It's about the computation of the F-measure. I already raised this issue once but now something changed. There are two ways to compute the macro F-measure.
1) as an average of the F-measures of each question
2) as (2*macro_precision*marco_recall)/(macro_precision+marco_recall).
You are currently using the first definition. But I'm for the second. There are two reasons.
1) All QALD challanges have been evaluated like this. (Here is  the evaluation script for QALD 6 by Cunger see line 178 https://github.com/ag-sc/QALD/blob/master/6/scripts/evaluation.rb). This argument I already reported once to Michael Roder.
2) The second I discovered recently. Imagine two QA systems QAS1 and QAS2. QAS1 can answer correctly 50 question and 50 not. But it will give an answer to all 100 questions. The F-score will be 50 %. The second QAS2 will answer 50 correctly and from the other it will say I do not know, i.e. it will not reply. If the F-measure is computed as in case 1 then the F-measure will be 50% again (each of the non answered question has precision 1, recall 0 and f-measure 0). In the second case the QAS will have f-measure 0.666. So there is a difference. So the definition 1 will say no difference even if there is one. 
Finally the advantage of definition 2 is that the f-measure is always between precision and recall which is not the case for the first situation. 

i.e. the request is, can you please change also how you compute the f-measure?

**Comment by RicardoUsbeck** [comment] 2017-09-29 11:55
We will discuss that internally on Monday. #Nodeployfriday Thanks for the arguments

**Comment by D063520** [comment] 2017-10-03 08:55
Hello, 

any news about the last point?

Salut
Dennis

P.S. our QA system was updated to curl --data "query=Who is the wife of Barack Obama" https://wdaqua-qanary.univ-st-etienne.fr/gerbil-execute/wdaqua-core1,%20QueryExecuter/. There is only one QA system available for both dbpedia and wikidata. If nothing is said then wikidata in english is queried. We support now also french, german, italian and spanish on dbpedia. I would suggest to add from the gerbil side a parameter similar to the language parameter to set the knowledge base.

**Comment by D063520** [comment] 2017-10-04 14:39
Hi Michael, 

thank you for your long response. I'm sorry but I'm still not convinced.

About 1 I would say it is not a big problem since there was no serious evaluation using Gerbil for QA since 2014. In fact we have seen that the measures were wrong. I'm not aware of any paper citing the measures which hopefully will change in the future (I really would like in fact and I'm near to do it since I now start to trust the measures). Moreover this way you will not be backwards compatible to all the QALD challenges lunched so far, which is a real problem in my eyes. 

My main problem is that if you set the precision to 0 you will be currently not able to measure an important thing about a QA system, namely the ability to say I do not know or I'm not sure. Instead of giving a random answer it is preferable that it gives no answer. As you set the metrics you will not be able to measure this important behaviour. Do you not care about this?

Can you send me a link to a publication were the f-measure is computed as you mentioned. In my survey paper for example I defined it the way I'm saying.

Salut
Dennis

**Comment by TortugaAttack** [comment] 2017-10-04 14:44
an additional argument for the current implementation: 

The f1 measure as you defined can still be calculated right now, while the current implementation could not if the other definition would be used. May not the best argument but still important to keep in mind.

**Comment by MichaelRoeder** [comment] 2017-10-04 16:11
### Macro F1-measure

I see that we are arguing about two different things here: You are focusing on your QA field while I also have the knowledge extraction and other fields in mind, in which we are using GERBIL (or parts of it). I think that it would be possible to have one implementation for the macro F1-measure for one of the fields and another for the other fields, but I want to avoid things like that. They are simply very confusing and not helpful in most cases :wink: 

The backwards compatibility of QALD is not given, anyway (AFAIK). For some datasets, the answers are not available anymore. For others, the answers are there but the KBs have been updated and are not matching the answers. I think in generell, QALD has a problem regarding the repeatability of experiments. The macro F1-measure seems to be a minor problem.

I see your problem, but please let us __separate__ these two problems from each other (see below). Otherwise, it becomes even more confusing.

You can simply search for macro F1-measure and you will find the different definitions, e.g., (after 3 minutes of search) http://www.jmlr.org/papers/volume3/forman03a/forman03a.pdf : _One is the macro-averaged F-measure, which is the traditional arithmetic mean of the F-measure computed for each problem._

@TortugaAttack gave a good argument as well.

### Empty responses

I see your point that an intelligent system that returns no answer might be better than a system returning some random answer hoping that it might guess a correct answer. Now, there are different ways to handle that.
Yes, one could define that the precision of an empty response is 1. But imagine a system that can not answer one single question - maybe it is even a dummy that does nothing. It would receive an overall macro precision of 1. I don't think that this reflects the performance of the system correctly, but I understand if somebody would accept this.

On the other hand, we have the micro measures, which can already express this. If the micro precision is high but the macro precision is not, you can see that the system was right, when it was sure that it could answer. If both is low, you have a guessing system. (If both are 0, it was a dummy that didn't answer anything :grinning:)

Although I see the disadvantage of the micro measures (large answer sets become more important than short sets), I think with micro/macro precision, recall and F1-measure, we already have a lot of good measures. We just have to make sure to interpret them correctly :wink:

**Closed** 2017-10-17 16:24 UTC

**Comment by D063520** [comment] 2017-10-23 08:58
Precision 1 (how to justify)
QALD: Cunger see line 178 https://github.com/ag-sc/QALD/blob/master/6/scripts/evaluation.rb).
WebQuestions: https://worksheets.codalab.org/bundles/0x40ca1b0bce3940c39bdbd02bea957e3f/

**Comment by D063520** [comment] 2017-10-23 09:04
For SimpleQuestions:
https://arxiv.org/pdf/1506.02075.pdf
Since they do not say nothing about the f-measure and there is no evaluation script in the repository:
https://research.fb.com/downloads/babi/
I think they reuse the same metrics

**Comment by TortugaAttack** [comment] 2017-10-23 11:53
will fix this on Thursday

**Comment by MichaelRoeder** [comment] 2017-10-24 16:55
From my point of view, both implementations simply show the violation of their own interpretation when you compare the implementation of the recall with the implementation of the precision. The first part of the script of Cunger is the same logic that we use in GERBIL as well (I added some comments to ease the reading):
```python
        # OUT OF SCOPE questions
        if comp[:total_gold] == 0
	   # The question has no answers in the gold standard
           if comp[:total_user] == 0
              # The system returned no answers
              precision = 1
              recall    = 1
              f1        = 1
           else
              # The system returned at least one answer
              precision = 0
              recall    = 0
              f1        = 0
           end
        # all other questions
        else
           if comp[:total_user] == 0
              # The system returned no answers
              precision = 1
           else
              # normal case
              precision = comp[:correct].to_f / comp[:total_user].to_f
           end
           recall = comp[:correct].to_f / comp[:total_gold].to_f
           f1 = fscore(precision,recall)
        end
```
The difference comes in the else block with `if comp[:total_user] == 0` and `precision = 1`.  But why is the recall set to `0` (as it is done in GERBIL) if the gold standard answers are empty but the results of the system are not? I would have assumed that if you interpret `0/0 = 1` for the precision, the same would be done for the recall...
The same holds for the other evaluation script that you mentioned. 
```
  """Assume all questions have at least one answer"""
  if len(goldList)==0:
    raise Exception("gold list may not be empty")
```
It does not even take this case into account. Apart from that, I am not convinced by the second script. I think that you could even cheat and increase your precision by repeating answers for which you are very sure that they are correct. As far as I understand the script, it will interpret all of them as correct, although you are simply repeating yourself. I am afraid that the same even holds for the script of Cunger. However, my python skills are not that good, to be 100% sure :wink:
But with GERBIL, this wouldn't be possible :smiley:

Regarding the paper https://arxiv.org/pdf/1506.02075.pdf, the authors do not have a definition of precision, recall or F1-score. They only write
> [...] in terms of F1-score as defined in (Berant and Liang, 2014), [...]

However, the paper that is cited (http://www.anthology.aclweb.org/P/P14/P14-1133.pdf) does only use accuracy and no F1-score. So it is not clear which definition they are using.
