### ISSUE TITLE
SSL certifcate problem

### ISSUE THREAD

**Issue by jheinecke** [dice-group/gerbil#366] opened 2020-11-05 17:42 UTC
`./start.sh` runs into a problem when downloading `http:/139.18.2.164/mroeder/gerbil/dbpedia_index.zip`:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
```
The same happens for `http:/139.18.2.164/mroeder/gerbil/dbpedia_check_index.zip`

**Comment by TortugaAttack** [comment] 2020-11-05 17:48
Hmm. 
Thats weird. It clearly is HTTP not HTTPS. 
Do you use something that switches HTTP to HTTPS automatically? Normally Curl should ignore the SSL certificate if it is http :thinking:

**Comment by jheinecke** [comment] 2020-11-05 17:50
I thought so too. I just ran `./start.sh` as said in the doc. It failed on a machine without firewall, so definitely no proxy/firewall issue

**Comment by TortugaAttack** [comment] 2020-11-05 17:53
weird. I will have a detailed look tomorrow and try to reproduce it.

**Comment by jheinecke** [comment] 2020-11-05 17:58
`wget http:/139.18.2.164/` returns a "301 Moved permanently" to  `https:/139.18.2.164/`. This explains the SSL error

**Comment by TortugaAttack** [comment] 2020-11-05 18:03
Yeah, the issue is server-side. 
I will move the files tomorrow to a different server, thus allowing https using a valid ssl script.

**Comment by jheinecke** [comment] 2020-11-05 18:09
great, thanks!

**Comment by MichaelRoeder** [comment] 2020-11-06 17:52
If you don't want to wait for a fix of the script, you can download the two indexes ([`dbpedia_index.zip`](https://hobbitdata.informatik.uni-leipzig.de/gerbil/dbpedia_index.zip) and [`dbpedia_check_index.zip`](https://hobbitdata.informatik.uni-leipzig.de/gerbil/dbpedia_check_index.zip)) manually and extract them into `indexes/dbpedia` and `indexes/dbpedia_check`, respectively.

**Comment by jheinecke** [comment] 2020-11-06 18:51
Thanks! I took this files to continue. I still encounter many network errors (even with the dbpedia files installed)
Does Gerbil tries to access a public service when it runs the evaluation dataset of the OKE2015 Task 1 ? The only (successful) contact which Gerbil seems to make to my annotator is when I click "Add another Annotator" (and I see the test sentence in the log of my annotator)

**Comment by RicardoUsbeck** [comment] 2020-11-06 19:20
Is it possible that it is the owl:sameAs index @TortugaAttack @MichaelRoeder ? 🤔

**Comment by MichaelRoeder** [comment] 2020-11-07 10:43
Could you please paste some of these errors? Most probably GERBIL tries to retrieve `owl:sameAs` links be dereferencing the IRIs found in the dataset. However, we need to have a look at the error message if we should ensure that it is the dereferencing part.

If you want to deactivate this functionality (which is reasonable since you have downloaded the index files), you can find a description how to do that in #130.

**Comment by RicardoUsbeck** [comment] 2020-11-07 10:50
We might want to document it in the wiki 🤷🏻‍♂️

**Comment by jheinecke** [comment] 2020-11-09 08:01
There are error messages when dealing with dbpedia entities

```
2020-11-06 19:47:40,880 [pool-1-thread-1] INFO [org.aksw.gerbil.semantic.sameas.impl.http.HTTPBasedSameAsRetriever] - <Exception while sending request to "http://dbpedia.org/resource/Minister_%28Christianity%29". Returning null.>
java.net.SocketException: Le réseau n'est pas accessible (connect failed)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
```
But also for wikipedia

```
2020-11-06 19:47:40,930 [pool-1-thread-1] ERROR [org.aksw.gerbil.semantic.sameas.impl.wiki.WikipediaApiBasedSingleUriSameAsRetriever] - <Got an exception while querying the wiki api of "en.wikipedia.org". Returning null.>
GerbilException: Exception while sending request. (error type -106: Got an unexpected exception while running the experiment.)
	at org.aksw.gerbil.http.AbstractHttpRequestEmitter.sendRequest(AbstractHttpRequestEmitter.java:172)
	at org.aksw.gerbil.http.AbstractHttpRequestEmitter.sendRequest(AbstractHttpRequestEmitter.java:145)
	at org.aksw.gerbil.semantic.sameas.impl.wiki.WikipediaApiBasedSingleUriSameAsRetriever.queryRedirect(WikipediaApiBasedSingleUriSameAsRetriever.java:102)
	at org.aksw.gerbil.semantic.sameas.impl.wiki.WikipediaApiBasedSingleUriSameAsRetriever.retrieveSameURIs(WikipediaApiBasedSingleUriSameAsRetriever.java:66)
	at org.aksw.gerbil.semantic.sameas.impl.DomainBasedSameAsRetrieverManager.retrieveSameURIs(DomainBasedSameAsRetrieverManager.java:70)
```

Since I sit behind a firewall, I cannot open the network to acces dbpedia and wikipedia, but I do not see the necessity to do so in the first place. I'll check the issue 130 to overcome this problem

**Comment by jheinecke** [comment] 2020-11-09 08:34
I tried modifying `gerbil.properties` and `entity_checking.properties`, but it still ties to connect to the external sites. 
By the way, I have downloaded `dbpedia_index.zip` and `dbpedia_check_index.zip` and run `start.sh` which extracts them to `indexes/dbpedia` and `indexes/dbpedia_check`; however looking at  `entity_checking.properties` I get the impression that the path where gerbil looks at for them is rather  `gerbil_data/indexes/....` which one is the correct one?

**Comment by MichaelRoeder** [comment] 2020-11-09 10:51
Yes, you are right. It looks like our start script has an issue with the paths of the indexes. @TortugaAttack can you please check it?

Yes, the indexes have to be in `gerbil_data/indexes/`.

As suggested by @RicardoUsbeck, I will create a description in the wiki that should clarify how to configure these things.

**Comment by jheinecke** [comment] 2020-11-09 10:54
the start script should create `gerbil_data/cache` too (otherwise the java process raises an exception.
Finally I commented enough stuff in the propertiy files, so it is running (correctly I hope)! Thanks

**Comment by MichaelRoeder** [comment] 2020-11-09 11:24
Yes, that is a good point.
@TortugaAttack can you please update the start script?

I have created a [documentation](https://github.com/dice-group/gerbil/wiki/Configuring-SameAs-retrieval) for the sameAs retrieval configuration. I will do the same for the entity checking later on.

**Comment by TortugaAttack** [comment] 2020-11-09 11:41
On it. 
Just need to figure out which of the indexes are the correct ones.

**Comment by TortugaAttack** [comment] 2020-11-09 11:50
should be fixed now. 
* uses the correct indexes from a server which allows https
* `gerbil_data/cache` will be created in the start script
* indexes will be unzipped in the correct folder

**Comment by jheinecke** [comment] 2020-11-09 16:27
Great, thanks! I've pulled it, and it looks good, thanks

**Closed** 2024-06-14 09:33 UTC
