### ISSUE TITLE
DBpedia Spotlight Spanish API - Unsupported Media Type Error

### ISSUE THREAD

**Issue by jmdu99** [dice-group/gerbil#386] opened 2021-04-14 11:00 UTC
Hello,

I'm trying to put the [DBpedia Spotlight API in Spanish](https://www.dbpedia-spotlight.org/api/es) in a GERBIL experiment (**Base url: api.dbpedia-spotlight.org/es**) and I'm getting this error:

**Unsupported Media Type**

![API_Gerbil](https://user-images.githubusercontent.com/48102058/114699362-7d33e780-9d20-11eb-9c1e-321424703b19.png)

Looking at the Wiki, I have seen that Rest APIs must support the _application / x-turtle_ type.
However, the Spotlight API supports the _text / turtle_ type, among others.
I was wondering if maybe I have put the URI of the REST service wrong or if it is necessary to add the _application / x-turtle_ type to the service for it to work.

Thank you very much in advance.
All the best

**Comment by MichaelRoeder** [comment] 2021-04-14 13:00
It seems like we expect the wrong media type. Following the [list of media types of the IANA](https://www.iana.org/assignments/media-types/media-types.xhtml) turtle should have `text/turtle`. It seems like the (older) application/x-turtle is not used, anymore. Maybe we should include both in our request (to ensure backward compatibility).

**Comment by jmdu99** [comment] 2021-04-14 13:15
> It seems like we expect the wrong media type. Following the [list of media types of the IANA](https://www.iana.org/assignments/media-types/media-types.xhtml) turtle should have `text/turtle`. It seems like the (older) application/x-turtle is not used, anymore. Maybe we should include both in our request (to ensure backward compatibility).

It could be. 

These are the types that the Spotlight API currently supports:

![Types_Spotlight](https://user-images.githubusercontent.com/48102058/114716210-1fa99600-9d34-11eb-87d7-e9314508d534.png)

**Comment by TortugaAttack** [comment] 2021-04-14 14:30
I tried it with `Accept: text/turtle`  and debugged it, 
The api.dbpedia-spotlight.org/es/annotate however returns content-type `text/plain`

**Comment by TortugaAttack** [comment] 2021-04-14 14:56
OK, this is a bigger issue. 
I tried it with text/turtle and it didn't work. 
The response cType isn't the problem here, the 415 comes from the initial content-type which we send as text/turtle in the nif format. 
However the es spotlight api doesn't allow that. In fact the only POST command I could get to work is the following:
```
curl 'https://api.dbpedia-spotlight.org/es/annotate' -H 'Accept: text/turtle' --data-raw 'text="This simple text is for testing the communication between the given web service and the GERBIL web service."'
```

So the problem is that we send the request as NIF (turtle) instead of "text=..."

**Comment by MichaelRoeder** [comment] 2021-04-14 15:02
I see... I guess we simply have a misunderstanding here :sweat_smile: 

@jmdu99 the web service interface that you try to configure is a NIF web service. This means that it accepts NIF as input and provides NIF as output. However, DBpedia Spotlight accepts only plain text as input. Hence, it does not follow the NIF service description and won't work with GERBIL in the way you try to configure it.

I think the easiest way to handle that might be to deploy GERBIL locally and adapt the URL of the DBpedia Spotlight service in the annotator.properties file.

**Comment by TortugaAttack** [comment] 2021-04-14 15:10
If you run it locally: 
Simply add the following to the annotators.propertes (located at src/main/properties/)

``` 
### DBpedia Spotlight ES
org.aksw.gerbil.annotators.definition.spotlight.name=DBpedia Spotlight ES
org.aksw.gerbil.annotators.definition.spotlight.experimentType=OKE_Task1
org.aksw.gerbil.annotators.definition.spotlight.cacheable=true
org.aksw.gerbil.annotators.definition.spotlight.class=org.aksw.gerbil.annotator.impl.spotlight.SpotlightAnnotator
org.aksw.gerbil.annotator.impl.spotlight.SpotlightAnnotator.ServieURL=https://api.dbpedia-spotlight.org/es/

```

**Comment by jmdu99** [comment] 2021-04-14 15:11
So if I change _https://api.dbpedia-spotlight.org/en/_  to _https://api.dbpedia-spotlight.org/es/_ , it should work?

Also another option could be to configure Spotlight to receive turtle and return turtle?

**Comment by TortugaAttack** [comment] 2021-04-14 15:13
exactly. 

returning NIF (turtle) works, it's just the receiving part which spotlight doesn't allow :)

**Comment by TortugaAttack** [comment] 2021-04-14 15:14
For the record: 
added this to the wiki at https://github.com/dice-group/gerbil/wiki/Available-APIs-and-approaches

**Comment by MichaelRoeder** [comment] 2021-04-14 15:18
The original issue is solved and the mime type strings have been updated in `gerbil.nif.transfer`. Hence, we will close the issue.

@jmdu99 Feel free to reopen / create a new issue in case you encounter another problem.

**Closed by MichaelRoeder** 2021-04-14 15:18 UTC
Labels: priority:high, type:bug

**Comment by jmdu99** [comment] 2021-04-14 15:24
Great, thank you so much
What if I want to add a modified Spotlight instance, that is, with a different URL? (I intend to deploy a Spotlight service that I am modifying)
It would be adding the same `annotators.properties` lines but changing
`org.aksw.gerbil.annotator.impl.spotlight.SpotlightAnnotator.ServieURL`?

**Comment by TortugaAttack** [comment] 2021-04-14 15:29
as the long as the modified instance follows the same principles (annotate, spot, disambiguate) you would only need to change the serviceURL yes

**Comment by jmdu99** [comment] 2021-04-14 15:32
Perfect, thank you!

**Comment by MichaelRoeder** [comment] 2021-04-14 16:08
Just to avoid misunderstandings and a lot of effort on your side: You can also easily add several instances of Spotlight to your annotators.properties (e.g., the original instance and your own). However, when adding more of them, you should ensure that they have different keys. Please have a look at [the corresponding section in our wiki](https://github.com/dice-group/gerbil/wiki/How-to-add-a-new-Annotator#add-the-annotator-permanently) for a description :wink:

**Comment by jmdu99** [comment] 2021-04-14 16:29
Nice! Thank you very much
