### ISSUE TITLE
GERBIL: "The annotator caused too many single errors."

### ISSUE THREAD

**Issue by jmdu99** [dice-group/gerbil#385] opened 2021-03-23 21:03 UTC
Hi,

I would like to evaluate the accuracy of DBpedia Spotlight using my own datasets, but when I try to configure an experiment from the[ GERBIL experiment page](http://gerbil.aksw.org/gerbil/config) selecting DBpedia Spotlight, I get the following message: "The annotator caused too many single errors."

Below are photos of the configuration and the error message:

![gerbil](https://user-images.githubusercontent.com/48102058/112215800-13dd1f00-8c21-11eb-840d-bbcdf8d2b13b.png)

![error](https://user-images.githubusercontent.com/48102058/112215806-15a6e280-8c21-11eb-95d6-92d2aae2b619.png)

So far I have tried with the original DBpedia Spotlight dataset ('dbpedia-spotlight-nif.ttl', downloaded from your [repository](https://github.com/dice-group/gerbil/releases/download/v1.2.6/gerbil_data.zip)). 

I have checked the syntax of the .ttl and it is correct. I have also seen the same error message being generated when selecting other custom datasets.

I would appreciate if you know what the error is due to, or if you can help me in any way.

Pd: soon I will be testing models that recognize both DBpedia and Wikidata entities, I wanted to know if there is any problem in having the **itsrdf: taIdentRef** property twice for each resource, or if it is better to have two separate datasets: a dataset to test DBpedia's entities and another for Wikidata's entities.

Thank you very much in advance.

**Comment by MichaelRoeder** [comment] 2021-03-24 11:22
If GERBIL states that the annotator caused the problems, it is very unlikely that your uploaded dataset caused it. In this case, we missed to correctly deploy the fix of #372 which updated the API URL of DBpedia Spotlight. It should work now.

Please check it again and close this issue in case the problem is solved for you.

You can assign several meanings using `itsrdf:taIdentRef` without causing any issues. Semantically, it simply means that your service states that all these IRIs you added there have the same meaning.

**Comment by jmdu99** [comment] 2021-03-24 16:55
It seems that now it does not give errors.
Thanks a lot!

How long does an experiment take to run?

**Closed** 2021-03-24 16:55 UTC
Labels: priority:severe, type:bug

**Comment by MichaelRoeder** [comment] 2021-03-24 17:04
The run time depends a lot on
* the size of the dataset
* the speed of the evaluated annotation service
* the number of different IRIs in the dataset and the result returned by the annotation service
* the status of the internal cache of GERBIL

However, because of the last two points, repeating an experiment typically takes less time than running it the first time.
