### ISSUE TITLE
Adding OpenTapioca to the available annotators

### ISSUE THREAD

**Issue by wetneb** [dice-group/gerbil#316] opened 2019-04-25 13:11 UTC
Hi!

First, thanks for maintaining GERBIL, it is a very useful tool!
If you are interested, I am running an entity linker for Wikidata at https://opentapioca.org/ which exposes a NIF endpoint at https://opentapioca.org/api/nif. It could be nice to add it to the list of available annotators, although it is already possible to add it manually as a webservice.

**Comment by MichaelRoeder** [comment] 2019-04-30 11:51
Added OpenTapioca
@wetneb please check the lines in https://github.com/dice-group/gerbil/commit/93c00d008a1b86a8f577c5f0c1343bb8b8167857 whether the name is correct.

However, the benchmark results are currently not correct, e.g., the two results of the annotator are counted as fp and fn although they are overlapping the expected set of URIs.
```
2019-04-30 12:44:57,628 [pool-1-thread-1] DEBUG [org.aksw.gerbil.matching.impl.MatchingsCounterImpl] - <Found a false negative ((0, 20, [http://dbpedia.org/resource/Florence_May_Harding, http://wikidata.org/entity/Q5460709, http://yago-knowledge.org/resource/Florence_May_Harding, http://en.wikipedia.org/wiki/Florence_May_Harding, http://www.ontologydesignpatterns.org/data/oke-challenge/task-1/Florence_May_Harding, http://wikidata.dbpedia.org/resource/Q5460709, http://rdf.freebase.com/ns/m.0h1d92w])).>
2019-04-30 12:44:57,628 [pool-1-thread-1] DEBUG [org.aksw.gerbil.matching.impl.MatchingsCounterImpl] - <Found a false negative ((44, 6, [http://en.wikipedia.org/wiki/Sydney, http://dbpedia.org/resource/Sydney_(Australia), http://wikidata.org/entity/Q3130, ...])).>
2019-04-30 12:44:57,628 [pool-1-thread-1] DEBUG [org.aksw.gerbil.matching.impl.MatchingsCounterImpl] - <Found a false positive ((44, 6, [http://www.wikidata.org/entity/Q3130])).>
2019-04-30 12:44:57,628 [pool-1-thread-1] DEBUG [org.aksw.gerbil.matching.impl.MatchingsCounterImpl] - <Found a false positive ((0, 20, [http://www.wikidata.org/entity/Q5460709])).>
```

**Comment by wetneb** [comment] 2019-04-30 12:11
Many thanks, that is wonderful! And I am very interested in the scoring issues of course, since it could potentially increase the scores I reported in the paper :)

(By the way it looks like we both used "Tapioca" to name our projects - sorry about this conflict, if I knew I would have picked another name!)

**Comment by MichaelRoeder** [comment] 2019-04-30 12:39
The issue is pretty easy :smile: 
Our sameAs retrieval returns the wrong domain for Wikidata entities, i.e., Sydney is represented as `http://wikidata.org/entity/Q5460709` while the annotator returns the correct URI `http://www.wikidata.org/entity/Q5460709`.

Since http://dbpedia.org/resource/Sydney links to `http://www.wikidata.org/entity/Q5460709`, I would assume that our index is outdated. @TortugaAttack could you please check whether the issue is caused by outdated data in the index?

(@wetneb no problem. I am happy that you named it "OpenTapioca" which makes it easier to distinguish them :wink: )

**Comment by MichaelRoeder** [comment] 2019-04-30 13:26
A run without cached data, without the DBpedia index and with HTTP-based retrieval enabled solves the problem. So the index is simply outdated.
@TortugaAttack we need to update the index.

**Comment by wetneb** [comment] 2019-08-06 13:41
If there is anything I can help with to move forward on this, let me know :) From my understanding it is simply a matter of merging 93c00d0 and updating the index, which I cannot do on your instance.

**Comment by MichaelRoeder** [comment] 2019-08-22 11:57
Please excuse the long delay. We had some issues to update the indexes.

![gerbil aksw org gerbil experiment id=201908220000](https://user-images.githubusercontent.com/6122307/63512668-aae17280-c4e4-11e9-8d2c-fec6e1aaa448.png)

http://gerbil.aksw.org/gerbil/experiment?id=201908220000
Please close the issue if it works for you :smiley:

**Comment by wetneb** [comment] 2019-08-22 12:05
Thanks a lot! I will add a PR to enable it for A2KB too.

**Closed** 2019-08-22 12:06 UTC
Labels: bug, enhancement
